In [1]:
import sklearn
import pandas as pd
import numpy as np

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from  sklearn.datasets import load_digits

In [3]:
digits=load_digits()
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [4]:
print(len(x_train))
print(len(y_train))

1257
1257


*Linear Regression*

In [40]:
lr=LogisticRegression(max_iter=200)
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

0.9165275459098498

*Using SVM*

In [6]:
svm=SVC()
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.9851851851851852

*Using Random Forest* 

In [7]:
rf=RandomForestClassifier(n_estimators=50)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.9703703703703703

In [9]:
def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [10]:
get_score(RandomForestClassifier(), x_train, x_test, y_train, y_test)

0.9722222222222222

### K_fold

In [33]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)

In [34]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [35]:
from sklearn.model_selection import StratifiedKFold
skf=StratifiedKFold(n_splits=3)

In [45]:
lr_score=[]
rf_score=[]
svc_score=[]


for train_index, test_index in skf.split(digits.data, digits.target):
    # Split the data into training and testing sets
    x_train, x_test = digits.data[train_index], digits.data[test_index]
    y_train, y_test = digits.target[train_index], digits.target[test_index]

    # Call get_score function (make sure it's defined)
    lr_score.append(get_score(LogisticRegression(max_iter=200), x_train, x_test, y_train, y_test))
    rf_score.append(get_score(RandomForestClassifier(n_estimators=40), x_train, x_test, y_train, y_test))
    svc_score.append(get_score(SVC(), x_train, x_test, y_train, y_test))


In [46]:
print(lr_score)
print(rf_score)
print(svc_score)

[0.9198664440734557, 0.9415692821368948, 0.9165275459098498]
[0.9382303839732888, 0.9449081803005008, 0.9332220367278798]
[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]


*Alternate* 

In [47]:
from sklearn.model_selection import cross_val_score

In [50]:
cross_val_score(LogisticRegression(max_iter=200), digits.data, digits.target)

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

In [51]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [53]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.93611111, 0.89722222, 0.95821727, 0.97214485, 0.91922006])

*Then after you have to do the parameter tuning to get the best result from your validation*